api:
  url: http://openapi.seoul.go.kr:8088/
  CycleStationInfo:
    key: 4265464a716a696e34324d4c646f79
    type: json
    service: tbCycleStationInfo

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1q2w3e4r!@
    driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        show_sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: jinyngg@gmail.com
    password: ebfrmjupncqpfgcu
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  jwt:
    secret: c3ByaW5nLWJvb3Qtc3RvcmUtcmVzZXJ2YXRpb24tcHJvamVjdC1qc29uLXdlYi10b2tlbi1zZWNyZXQta2V5


scheduler:
  cycleStation:
    test:
      cron: "0/30 * * * * *"
    cron: "0 0 0 * * *"

