api:
  url: http://openapi.seoul.go.kr:8088/
  bikeMaster:
    key: 706f46794e6a696e373761666e6771
    type: json
    service: bikeStationMaster

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1q2w3e4r!@
    driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        show_sql: true

